### ISSUE TITLE
Send out the result of task processing

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-compiler-fleet#11]
When compiler instance completes processing a task, it needs to send out the result. 

The result is also a protocol buffer which is sent to PubSub topic. It needs to include:
* task id -- the same which was received in the task message)
* status code -- integer number, 0 in case of success and other value in case of errors. The semantics of non-zero codes will be established later
* result itself. It should be a byte array which currently (when we calculate md5) may be just a string. Later when we start producing PDF it will be a serialized PDF document and finally in production it most likely will be a serialized protocol buffer with the information about the produced artifacts.

**Comment by shavkunov** [comment]
I guess, we need new topic for publishing results and new subscription to that topic.

**Comment by dbarashev** [comment]
`rmarkdown-resuls` is the topic name and there is a subscription called `test`

**Comment by shavkunov** [comment]
I hope, that is ```rmarkdown-results``` :)

**Comment by dbarashev** [comment]
Right,` rmarkdown-results`, sorry for the typo
