### ISSUE TITLE
Really process project by rmarkdown compiler

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-compiler-fleet#12]
Googling "docker rmarkdown" produces a handful of results and it seems there are existing options of compiling RMarkdown documents in Docker. So we need to take some of the existing images and feed it with the project extracted from ZIP. For that purpose we'll need to bind-mount the directory where project was extracted to into the container and, well, run the compiler.

**Comment by shavkunov** [comment]
Is it okay compile Rmd files into PDF?
I found this [repo](https://github.com/briandk/manuscribble)
Compile command looks pretty simple

**Comment by dbarashev** [comment]
1. Yes, the final result of compilation should be PDF
1. It would be nice if RMarkdown could emit PDF directly without LaTeX, but if LaTeX is required anyway then in production we will either
    1. use either image built from our own LaTeX images (to avoid maintaining too many assorted latexz here and there) or 
    1. produce LaTeX from RMarkdown and then compile LaTeX to PDF using our existing approach
1. However, for current development needs it is okay to use existing image :)
