### ISSUE TITLE
Command line utility for publishing ZIP tasks

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-compiler-fleet#14]
Let's convert our publisher into a command line utility which can be invoked with the directory name in the arguments and which will create a zIP archive and will send it to the topic?

**Comment by shavkunov** [comment]
What about taskId and rootFileName?
Or I need to publish only zip to the topic?

**Comment by dbarashev** [comment]
You can invent your own task id. Root file name is required of course, unless the whole ZIP consists of a single file. You can pass its name in the arguments.

**Comment by shavkunov** [comment]
> You can invent your own task id.

I'm computing hash of zipped data. Do I need to generate new task id every time of the same zipped task?

**Comment by dbarashev** [comment]
Hash is okay for CLI purposes
